name: Build and test/lint/format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "0.7.13"
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Run linter
      run: uvx ruff check
    - name: Run formatter
      run: uvx ruff format --check
    - name: Run tests
      run: uv run pytest --cov
    - name: Creating coverage folder
      run: |
        mkdir -p coverage
    - name: Coverage Badge
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: coverage/coverage.svg
    - name: Publish coverage report to coverage-badge branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: coverage
        ssh-key: ${{ secrets.DEPLOY_KEY }}
