name: Build and test/lint/format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "0.7.13"
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Run linter
      run: uvx ruff check
    - name: Run formatter
      run: uvx ruff format --check
    - name: Run tests
      run: uv run pytest --cov=src
    - name: Run doc-builder
      run: uvx --with mkdocs-material mkdocs build
